version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: journal_app_serverpod
      POSTGRES_PASSWORD: "Zss8PJXTnyHbFN57TWeow28j8cLE-KQo"
    volumes:
      - journal_app_serverpod_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "C6noZQ8Gsi2qbpr07QJgECm9eu7LGF1y"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  journal_app_serverpod_data:
